"""empty message

Revision ID: 721bd2a98059
Revises: 17cb4274c8b7
Create Date: 2023-11-30 11:16:51.850377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721bd2a98059'
down_revision = '17cb4274c8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
