"""empty message

Revision ID: df926bbc520a
Revises: b68c24b16a40
Create Date: 2023-11-30 12:33:50.299661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df926bbc520a'
down_revision = 'b68c24b16a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_admin_id'), ['admin_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_admin_id_admin'), 'admin', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_admin_id_admin'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_admin_id'))
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
